{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "tests\\ui\\test_login_page.py:20: in test_login_negative\n    login_page.login_negative(CLICKUP_EMAIL, '12345')\npages\\login_page.py:42: in login_negative\n    self.navigate_to()\npages\\base_page.py:19: in navigate_to\n    self.page.goto(full_url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE   playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nE   Call log:\nE     - navigating to \"https://app.clickup.com/login\", waiting until \"load\""}, "description": "Проверка невозможности авторизации с некорректными данными (негативный тест).", "steps": [{"name": "Открытие страницы входа и попытка авторизации с некорректными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\tests\\ui\\test_login_page.py\", line 20, in test_login_negative\n    login_page.login_negative(CLICKUP_EMAIL, '12345')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 19, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Неудачная авторизация с логином: 'milanakan2001@gmail.com' и неверным паролем: '12345'", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 19, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход на страницу входа", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 19, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход по URL страницы", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 19, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1744812636416, "stop": 1744812644355}], "start": 1744812636416, "stop": 1744812644357}], "parameters": [{"name": "username", "value": "'milanakan2001@gmail.com'"}, {"name": "password_invalid", "value": "'12345'"}], "start": 1744812636416, "stop": 1744812644359}], "start": 1744812635945, "stop": 1744812644362}], "start": 1744812635945, "stop": 1744812644365, "uuid": "b04df7de-d7b1-47d1-9125-f903d9a81e06", "historyId": "21f5678c3abeecd832fe4240961d2fdf", "testCaseId": "21f5678c3abeecd832fe4240961d2fdf", "fullName": "tests.ui.test_login_page#test_login_negative", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "13368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}