{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Попытка обновления задачи с некорректными данными", "status": "passed", "steps": [{"name": "Обновление задачи по ID: '86c3421hn'", "status": "passed", "steps": [{"name": "PUT /task/86c3421hn", "status": "passed", "start": 1744809347258, "stop": 1744809347454}], "parameters": [{"name": "task_id", "value": "'86c3421hn'"}, {"name": "task_update", "value": "'invalid_text'"}], "start": 1744809347258, "stop": 1744809347454}], "start": 1744809347257, "stop": 1744809347454}], "start": 1744809347257, "stop": 1744809347454, "uuid": "014d8ece-9507-4c2e-8856-210cec10b201", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "8820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}