{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Попытка обновления задачи с некорректными данными", "status": "passed", "steps": [{"name": "Обновление задачи по ID: '86c33r312'", "status": "passed", "steps": [{"name": "PUT /task/86c33r312", "status": "passed", "start": 1744790593685, "stop": 1744790593849}], "parameters": [{"name": "task_id", "value": "'86c33r312'"}, {"name": "task_update", "value": "'invalid_text'"}], "start": 1744790593685, "stop": 1744790593849}], "start": 1744790593685, "stop": 1744790593849}], "start": 1744790593684, "stop": 1744790593849, "uuid": "349df350-4c98-450c-87b6-21ca7fdabe39", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "13988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}