{"name": "test_create_task_ui", "status": "broken", "statusDetails": {"message": "KeyError: 'username'", "trace": "tests\\ui\\conftest.py:30: in logged_in_page\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\nE   KeyError: 'username'"}, "description": "Создание задачи через UI, проверка её наличия через API и удаление через API", "start": 1744809426110, "stop": 1744809426110, "uuid": "5e2b1eb0-5774-444e-8fb0-0bc0a0be4c23", "historyId": "2a3b88328967e738dee09645e036d697", "testCaseId": "2a3b88328967e738dee09645e036d697", "fullName": "tests.ui.test_board_page#test_create_task_ui", "labels": [{"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_board_page"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "10288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_board_page"}]}