{"name": "test_create_task_ui", "status": "broken", "statusDetails": {"message": "KeyError: 'username'", "trace": "tests\\ui\\conftest.py:30: in logged_in_page\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\nE   KeyError: 'username'"}, "description": "Создание задачи через UI, проверка её наличия через API и удаление через API", "start": 1744809434493, "stop": 1744809434493, "uuid": "9d4ea256-1a6a-4057-a31e-3b0e56c60e08", "historyId": "2a3b88328967e738dee09645e036d697", "testCaseId": "2a3b88328967e738dee09645e036d697", "fullName": "tests.ui.test_board_page#test_create_task_ui", "labels": [{"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_board_page"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_board_page"}]}